### ISSUE TITLE
Cannot install on Ubuntu and Windows

### ISSUE THREAD

**Issue by Tomino2112** [dberesford/exiv2node#33]
Hi,

I am trying to install this for quite some time already, but always fail on node-gyp. Any advice?

Content of npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'exiv2',
1 verbose cli   '--verbose' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 silly cache add args [ 'exiv2', null ]
5 verbose cache add spec exiv2
6 silly cache add parsed spec { raw: 'exiv2',
6 silly cache add   scope: null,
6 silly cache add   name: 'exiv2',
6 silly cache add   rawSpec: '',
6 silly cache add   spec: '*',
6 silly cache add   type: 'range' }
7 verbose addNamed exiv2@*
8 silly addNamed semver.valid null
9 silly addNamed semver.validRange *
10 silly addNameRange { name: 'exiv2', range: '*', hasData: false }
11 silly mapToRegistry name exiv2
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry uri https://registry.npmjs.org/exiv2
15 verbose addNameRange registry:https://registry.npmjs.org/exiv2 not in flight; fetching
16 verbose request uri https://registry.npmjs.org/exiv2
17 verbose request no auth needed
18 info attempt registry request try #1 at 8:48:35 PM
19 verbose request id 99592040d31d69e6
20 verbose etag "898K9H978TCX8H5NVQIC9079U"
21 http request GET https://registry.npmjs.org/exiv2
22 http 304 https://registry.npmjs.org/exiv2
23 silly get cb [ 304,
23 silly get   { date: 'Sun, 15 Mar 2015 19:48:46 GMT',
23 silly get     server: 'Apache',
23 silly get     via: '1.1 varnish',
23 silly get     'last-modified': 'Sun, 15 Mar 2015 19:48:46 GMT',
23 silly get     'cache-control': 'max-age=60',
23 silly get     etag: '"898K9H978TCX8H5NVQIC9079U"',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-lhr6323-LHR',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1426448926.587231,VS0,VE360',
23 silly get     vary: 'Accept',
23 silly get     'content-length': '0',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose etag https://registry.npmjs.org/exiv2 from cache
25 verbose get saving exiv2 to /home/tomino/.npm/registry.npmjs.org/exiv2/.cache.json
26 silly addNameRange number 2 { name: 'exiv2', range: '*', hasData: true }
27 silly addNameRange versions [ 'exiv2',
27 silly addNameRange   [ '0.0.1',
27 silly addNameRange     '0.1.0',
27 silly addNameRange     '0.1.1',
27 silly addNameRange     '0.2.0',
27 silly addNameRange     '0.3.0',
27 silly addNameRange     '0.4.0',
27 silly addNameRange     '0.3.1',
27 silly addNameRange     '0.4.1',
27 silly addNameRange     '0.4.3',
27 silly addNameRange     '0.5.0' ] ]
28 verbose addNamed exiv2@0.5.0
29 silly addNamed semver.valid 0.5.0
30 silly addNamed semver.validRange 0.5.0
31 silly cache afterAdd exiv2@0.5.0
32 verbose afterAdd /home/tomino/.npm/exiv2/0.5.0/package/package.json not in flight; writing
33 verbose afterAdd /home/tomino/.npm/exiv2/0.5.0/package/package.json written
34 silly install resolved [ { author:
34 silly install resolved      { name: 'Damian Beresford',
34 silly install resolved        email: 'dberesford@gmail.com',
34 silly install resolved        url: 'http://www.damianberesford.com/' },
34 silly install resolved     name: 'exiv2',
34 silly install resolved     description: 'A native c++ extension for node.js that provides support for reading & writing image metadata via Exiv2.',
34 silly install resolved     version: '0.5.0',
34 silly install resolved     homepage: 'https://github.com/dberesford/exiv2node',
34 silly install resolved     repository:
34 silly install resolved      { type: 'git',
34 silly install resolved        url: 'git://github.com/dberesford/exiv2node.git' },
34 silly install resolved     dependencies: { nan: '>= 1.7.0' },
34 silly install resolved     devDependencies: { should: '*', mocha: '*' },
34 silly install resolved     optionalDependencies: {},
34 silly install resolved     engines: { node: '>= 0.9.4' },
34 silly install resolved     main: 'exiv2',
34 silly install resolved     scripts:
34 silly install resolved      { preuninstall: 'rm -rf build/*',
34 silly install resolved        test: 'mocha',
34 silly install resolved        install: 'node-gyp rebuild' },
34 silly install resolved     gypfile: true,
34 silly install resolved     contributors: [ [Object], [Object], [Object] ],
34 silly install resolved     bugs: { url: 'https://github.com/dberesford/exiv2node/issues' },
34 silly install resolved     gitHead: '997830ab490334c358226a814cd85800a228dddb',
34 silly install resolved     _id: 'exiv2@0.5.0',
34 silly install resolved     _shasum: 'bc8ff590255dc996289b01dd6810baaaa2494787',
34 silly install resolved     _from: 'exiv2@*',
34 silly install resolved     _npmVersion: '2.5.1',
34 silly install resolved     _nodeVersion: '0.12.0',
34 silly install resolved     _npmUser: { name: 'drewish', email: 'drewish@katherinehouse.com' },
34 silly install resolved     maintainers: [ [Object], [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'bc8ff590255dc996289b01dd6810baaaa2494787',
34 silly install resolved        tarball: 'http://registry.npmjs.org/exiv2/-/exiv2-0.5.0.tgz' },
34 silly install resolved     directories: {},
34 silly install resolved     _resolved: 'https://registry.npmjs.org/exiv2/-/exiv2-0.5.0.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install exiv2@0.5.0 into /media/win_www/imageSplitApp
36 info installOne exiv2@0.5.0
37 verbose installOne of exiv2 to /media/win_www/imageSplitApp not in flight; installing
38 verbose lock using /home/tomino/.npm/_locks/exiv2-d2680eb748b55649.lock for /media/win_www/imageSplitApp/node_modules/exiv2
39 silly install write writing exiv2 0.5.0 to /media/win_www/imageSplitApp/node_modules/exiv2
40 silly cache addNamed cb exiv2@0.5.0
41 verbose unbuild node_modules/exiv2
42 verbose gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2
43 verbose tar unpack /home/tomino/.npm/exiv2/0.5.0/package.tgz
44 verbose tar unpacking to /media/win_www/imageSplitApp/node_modules/exiv2
45 verbose gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2
46 silly gunzTarPerm modes [ '755', '644' ]
47 silly gunzTarPerm extractEntry package.json
48 silly gunzTarPerm extractEntry .npmignore
49 silly gunzTarPerm extractEntry README.md
50 silly gunzTarPerm extractEntry LICENSE
51 silly gunzTarPerm extractEntry exiv2.js
52 silly gunzTarPerm extractEntry binding.gyp
53 silly gunzTarPerm extractEntry AUTHORS
54 silly gunzTarPerm extractEntry examples/simple.js
55 silly gunzTarPerm extractEntry exiv2node.cc
56 silly gunzTarPerm extractEntry .travis.yml
57 silly gunzTarPerm extractEntry test/test.js
58 silly gunzTarPerm extractEntry test/images/books.jpg
59 silly gunzTarPerm extractEntry test/images/damien.jpg
60 silly gunzTarPerm extractEntry test/mocha.opts
61 info preinstall exiv2@0.5.0
62 silly prepareForInstallMany adding nan@>= 1.7.0 from exiv2 dependencies
63 silly cache add args [ 'nan@>= 1.7.0', null ]
64 verbose cache add spec nan@>= 1.7.0
65 silly cache add parsed spec { raw: 'nan@>= 1.7.0',
65 silly cache add   scope: null,
65 silly cache add   name: 'nan',
65 silly cache add   rawSpec: '>= 1.7.0',
65 silly cache add   spec: '>=1.7.0',
65 silly cache add   type: 'range' }
66 verbose addNamed nan@>=1.7.0
67 silly addNamed semver.valid null
68 silly addNamed semver.validRange >=1.7.0
69 silly addNameRange { name: 'nan', range: '>=1.7.0', hasData: false }
70 silly mapToRegistry name nan
71 silly mapToRegistry using default registry
72 silly mapToRegistry registry https://registry.npmjs.org/
73 silly mapToRegistry uri https://registry.npmjs.org/nan
74 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
75 verbose request uri https://registry.npmjs.org/nan
76 verbose request no auth needed
77 info attempt registry request try #1 at 8:48:36 PM
78 verbose etag "12EHA1PNRCCAOAQY0AIBQ9ET9"
79 http request GET https://registry.npmjs.org/nan
80 http 304 https://registry.npmjs.org/nan
81 silly get cb [ 304,
81 silly get   { date: 'Sun, 15 Mar 2015 19:48:47 GMT',
81 silly get     server: 'Apache',
81 silly get     via: '1.1 varnish',
81 silly get     'last-modified': 'Sun, 15 Mar 2015 19:48:47 GMT',
81 silly get     'cache-control': 'max-age=60',
81 silly get     etag: '"12EHA1PNRCCAOAQY0AIBQ9ET9"',
81 silly get     age: '54',
81 silly get     'x-served-by': 'cache-lhr6320-LHR',
81 silly get     'x-cache': 'HIT',
81 silly get     'x-cache-hits': '1',
81 silly get     'x-timer': 'S1426448927.568696,VS0,VE1',
81 silly get     vary: 'Accept',
81 silly get     'content-length': '0',
81 silly get     'keep-alive': 'timeout=10, max=50',
81 silly get     connection: 'Keep-Alive' } ]
82 verbose etag https://registry.npmjs.org/nan from cache
83 verbose get saving nan to /home/tomino/.npm/registry.npmjs.org/nan/.cache.json
84 silly addNameRange number 2 { name: 'nan', range: '>=1.7.0', hasData: true }
85 silly addNameRange versions [ 'nan',
85 silly addNameRange   [ '0.3.0-wip',
85 silly addNameRange     '0.3.0-wip2',
85 silly addNameRange     '0.3.0',
85 silly addNameRange     '0.3.1',
85 silly addNameRange     '0.3.2',
85 silly addNameRange     '0.4.0',
85 silly addNameRange     '0.4.1',
85 silly addNameRange     '0.4.2',
85 silly addNameRange     '0.4.3',
85 silly addNameRange     '0.4.4',
85 silly addNameRange     '0.5.0',
85 silly addNameRange     '0.5.1',
85 silly addNameRange     '0.5.2',
85 silly addNameRange     '0.6.0',
85 silly addNameRange     '0.7.0',
85 silly addNameRange     '0.7.1',
85 silly addNameRange     '0.8.0',
85 silly addNameRange     '1.0.0',
85 silly addNameRange     '1.1.0',
85 silly addNameRange     '1.1.1',
85 silly addNameRange     '1.1.2',
85 silly addNameRange     '1.2.0',
85 silly addNameRange     '1.3.0',
85 silly addNameRange     '1.4.0',
85 silly addNameRange     '1.4.1',
85 silly addNameRange     '1.5.0',
85 silly addNameRange     '1.4.2',
85 silly addNameRange     '1.4.3',
85 silly addNameRange     '1.5.1',
85 silly addNameRange     '1.5.2',
85 silly addNameRange     '1.6.0',
85 silly addNameRange     '1.5.3',
85 silly addNameRange     '1.6.1',
85 silly addNameRange     '1.6.2',
85 silly addNameRange     '1.7.0' ] ]
86 verbose addNamed nan@1.7.0
87 silly addNamed semver.valid 1.7.0
88 silly addNamed semver.validRange 1.7.0
89 silly cache afterAdd nan@1.7.0
90 verbose afterAdd /home/tomino/.npm/nan/1.7.0/package/package.json not in flight; writing
91 verbose afterAdd /home/tomino/.npm/nan/1.7.0/package/package.json written
92 silly install resolved [ { name: 'nan',
92 silly install resolved     version: '1.7.0',
92 silly install resolved     description: 'Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility',
92 silly install resolved     main: 'include_dirs.js',
92 silly install resolved     repository: { type: 'git', url: 'git://github.com/rvagg/nan.git' },
92 silly install resolved     scripts:
92 silly install resolved      { test: 'tap --gc test/js/*-test.js',
92 silly install resolved        'rebuild-tests': 'pangyp rebuild --directory test' },
92 silly install resolved     contributors:
92 silly install resolved      [ [Object],
92 silly install resolved        [Object],
92 silly install resolved        [Object],
92 silly install resolved        [Object],
92 silly install resolved        [Object],
92 silly install resolved        [Object],
92 silly install resolved        [Object] ],
92 silly install resolved     devDependencies:
92 silly install resolved      { bindings: '~1.2.1',
92 silly install resolved        'node-gyp': '~1.0.2',
92 silly install resolved        pangyp: '~2.0.1',
92 silly install resolved        tap: '~0.5.0',
92 silly install resolved        xtend: '~4.0.0' },
92 silly install resolved     license: 'MIT',
92 silly install resolved     gitHead: '550efb5dde5cb6bf79db87ab48dce850e56e971a',
92 silly install resolved     bugs: { url: 'https://github.com/rvagg/nan/issues' },
92 silly install resolved     homepage: 'https://github.com/rvagg/nan',
92 silly install resolved     _id: 'nan@1.7.0',
92 silly install resolved     _shasum: '755b997404e83cbe7bc08bc3c5c56291bce87438',
92 silly install resolved     _from: 'nan@>=1.7.0',
92 silly install resolved     _npmVersion: '2.5.1',
92 silly install resolved     _nodeVersion: '0.12.0',
92 silly install resolved     _npmUser: { name: 'kkoopa', email: 'bbyholm@abo.fi' },
92 silly install resolved     maintainers: [ [Object], [Object] ],
92 silly install resolved     dist:
92 silly install resolved      { shasum: '755b997404e83cbe7bc08bc3c5c56291bce87438',
92 silly install resolved        tarball: 'http://registry.npmjs.org/nan/-/nan-1.7.0.tgz' },
92 silly install resolved     directories: {},
92 silly install resolved     _resolved: 'https://registry.npmjs.org/nan/-/nan-1.7.0.tgz',
92 silly install resolved     readme: 'ERROR: No README data found!' } ]
93 info install nan@1.7.0 into /media/win_www/imageSplitApp/node_modules/exiv2
94 info installOne nan@1.7.0
95 verbose installOne of nan to /media/win_www/imageSplitApp/node_modules/exiv2 not in flight; installing
96 verbose lock using /home/tomino/.npm/_locks/nan-9a52ea733f606ba4.lock for /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
97 silly install write writing nan 1.7.0 to /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
98 silly cache addNamed cb nan@1.7.0
99 verbose unbuild node_modules/exiv2/node_modules/nan
100 verbose gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
101 verbose tar unpack /home/tomino/.npm/nan/1.7.0/package.tgz
102 verbose tar unpacking to /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
103 verbose gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
104 silly gunzTarPerm modes [ '755', '644' ]
105 silly gunzTarPerm extractEntry package.json
106 silly gunzTarPerm modified mode [ 'package.json', 436, 420 ]
107 silly gunzTarPerm extractEntry include_dirs.js
108 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 420 ]
109 silly gunzTarPerm extractEntry LICENSE.md
110 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 420 ]
111 silly gunzTarPerm extractEntry .dntrc
112 silly gunzTarPerm modified mode [ '.dntrc', 436, 420 ]
113 silly gunzTarPerm extractEntry appveyor.yml
114 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 420 ]
115 silly gunzTarPerm extractEntry nan.h
116 silly gunzTarPerm modified mode [ 'nan.h', 436, 420 ]
117 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
118 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 420 ]
119 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
120 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 420 ]
121 silly gunzTarPerm extractEntry nan_new.h
122 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 420 ]
123 silly gunzTarPerm extractEntry nan_string_bytes.h
124 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 436, 420 ]
125 silly gunzTarPerm extractEntry CHANGELOG.md
126 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 420 ]
127 info preinstall nan@1.7.0
128 silly install resolved []
129 verbose about to build /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
130 info build /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
131 verbose linkStuff [ false,
131 verbose linkStuff   false,
131 verbose linkStuff   false,
131 verbose linkStuff   '/media/win_www/imageSplitApp/node_modules/exiv2/node_modules' ]
132 info linkStuff nan@1.7.0
133 verbose linkBins nan@1.7.0
134 verbose linkMans nan@1.7.0
135 verbose rebuildBundles nan@1.7.0
136 info install nan@1.7.0
137 info postinstall nan@1.7.0
138 verbose unlock done using /home/tomino/.npm/_locks/nan-9a52ea733f606ba4.lock for /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
139 verbose about to build /media/win_www/imageSplitApp/node_modules/exiv2
140 info build /media/win_www/imageSplitApp/node_modules/exiv2
141 verbose linkStuff [ false,
141 verbose linkStuff   false,
141 verbose linkStuff   false,
141 verbose linkStuff   '/media/win_www/imageSplitApp/node_modules' ]
142 info linkStuff exiv2@0.5.0
143 verbose linkBins exiv2@0.5.0
144 verbose linkMans exiv2@0.5.0
145 verbose rebuildBundles exiv2@0.5.0
146 verbose rebuildBundles [ 'nan' ]
147 info install exiv2@0.5.0
148 verbose unsafe-perm in lifecycle false
149 info exiv2@0.5.0 Failed to exec install script
150 verbose unlock done using /home/tomino/.npm/_locks/exiv2-d2680eb748b55649.lock for /media/win_www/imageSplitApp/node_modules/exiv2
151 verbose stack Error: exiv2@0.5.0 install: `node-gyp rebuild`
151 verbose stack Exit status 1
151 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
151 verbose stack     at EventEmitter.emit (events.js:110:17)
151 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
151 verbose stack     at ChildProcess.emit (events.js:110:17)
151 verbose stack     at maybeClose (child_process.js:1008:16)
151 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
152 verbose pkgid exiv2@0.5.0
153 verbose cwd /media/win_www/imageSplitApp
154 error Linux 3.13.0-44-generic
155 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "exiv2" "--verbose"
156 error node v0.12.0
157 error npm  v2.5.1
158 error code ELIFECYCLE
159 error exiv2@0.5.0 install: `node-gyp rebuild`
159 error Exit status 1
160 error Failed at the exiv2@0.5.0 install script 'node-gyp rebuild'.
160 error This is most likely a problem with the exiv2 package,
160 error not with npm itself.
160 error Tell the author that this fails on your system:
160 error     node-gyp rebuild
160 error You can get their info via:
160 error     npm owner ls exiv2
160 error There is likely additional logging output above.
161 verbose exit [ 1, true ]
162 verbose unbuild node_modules/exiv2
163 info preuninstall exiv2@0.5.0
164 verbose unsafe-perm in lifecycle false
165 info uninstall exiv2@0.5.0
166 verbose unbuild rmStuff exiv2@0.5.0 from /media/win_www/imageSplitApp/node_modules
167 info postuninstall exiv2@0.5.0
168 verbose gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2
169 silly gentlyRm purging /media/win_www/imageSplitApp/node_modules/exiv2
170 silly gentlyRm quitting because other entries in /media/win_www/imageSplitApp/node_modules
```

Console output (using --verbose):

```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'exiv2',
npm verb cli   '--verbose' ]
npm info using npm@2.5.1
npm info using node@v0.12.0
npm verb cache add spec exiv2
npm verb addNamed exiv2@*
npm verb addNameRange registry:https://registry.npmjs.org/exiv2 not in flight; fetching
npm verb request uri https://registry.npmjs.org/exiv2
npm verb request no auth needed
npm info attempt registry request try #1 at 8:56:36 PM
npm verb request id cacf9beeaaeaa855
npm verb etag "898K9H978TCX8H5NVQIC9079U"
npm http request GET https://registry.npmjs.org/exiv2
npm http 304 https://registry.npmjs.org/exiv2
npm verb etag https://registry.npmjs.org/exiv2 from cache
npm verb get saving exiv2 to /home/tomino/.npm/registry.npmjs.org/exiv2/.cache.json
npm verb addNamed exiv2@0.5.0
npm verb afterAdd /home/tomino/.npm/exiv2/0.5.0/package/package.json not in flight; writing
npm verb afterAdd /home/tomino/.npm/exiv2/0.5.0/package/package.json written
npm info install exiv2@0.5.0 into /media/win_www/imageSplitApp
npm info installOne exiv2@0.5.0
npm verb installOne of exiv2 to /media/win_www/imageSplitApp not in flight; installing
npm verb lock using /home/tomino/.npm/_locks/exiv2-d2680eb748b55649.lock for /media/win_www/imageSplitApp/node_modules/exiv2
npm verb unbuild node_modules/exiv2
npm verb gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2
npm verb tar unpack /home/tomino/.npm/exiv2/0.5.0/package.tgz
npm verb tar unpacking to /media/win_www/imageSplitApp/node_modules/exiv2
npm verb gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2
npm info preinstall exiv2@0.5.0
npm verb cache add spec nan@>= 1.7.0
npm verb addNamed nan@>=1.7.0
npm verb addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 8:56:37 PM
npm verb etag "12EHA1PNRCCAOAQY0AIBQ9ET9"
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to /home/tomino/.npm/registry.npmjs.org/nan/.cache.json
npm verb addNamed nan@1.7.0
npm verb afterAdd /home/tomino/.npm/nan/1.7.0/package/package.json not in flight; writing
npm verb afterAdd /home/tomino/.npm/nan/1.7.0/package/package.json written
npm info install nan@1.7.0 into /media/win_www/imageSplitApp/node_modules/exiv2
npm info installOne nan@1.7.0
npm verb installOne of nan to /media/win_www/imageSplitApp/node_modules/exiv2 not in flight; installing
npm verb lock using /home/tomino/.npm/_locks/nan-9a52ea733f606ba4.lock for /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
npm verb unbuild node_modules/exiv2/node_modules/nan
npm verb gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
npm verb tar unpack /home/tomino/.npm/nan/1.7.0/package.tgz
npm verb tar unpacking to /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
npm verb gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
npm info preinstall nan@1.7.0
npm verb about to build /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
npm info build /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   '/media/win_www/imageSplitApp/node_modules/exiv2/node_modules' ]
npm info linkStuff nan@1.7.0
npm verb linkBins nan@1.7.0
npm verb linkMans nan@1.7.0
npm verb rebuildBundles nan@1.7.0
npm info install nan@1.7.0
npm info postinstall nan@1.7.0
npm verb unlock done using /home/tomino/.npm/_locks/nan-9a52ea733f606ba4.lock for /media/win_www/imageSplitApp/node_modules/exiv2/node_modules/nan
npm verb about to build /media/win_www/imageSplitApp/node_modules/exiv2
npm info build /media/win_www/imageSplitApp/node_modules/exiv2
npm verb linkStuff [ false,
npm verb linkStuff   false,
npm verb linkStuff   false,
npm verb linkStuff   '/media/win_www/imageSplitApp/node_modules' ]
npm info linkStuff exiv2@0.5.0
npm verb linkBins exiv2@0.5.0
npm verb linkMans exiv2@0.5.0
npm verb rebuildBundles exiv2@0.5.0
npm verb rebuildBundles [ 'nan' ]
npm info install exiv2@0.5.0

> exiv2@0.5.0 install /media/win_www/imageSplitApp/node_modules/exiv2
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ 'node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@1.0.2
gyp info using node@0.12.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `python -c "import platform; print(platform.python_version());"` returned: "2.7.3\n"
gyp verb get node dir no --target version specified, falling back to host node version: v0.12.0
gyp verb command install [ 'v0.12.0' ]
gyp verb install input version string "v0.12.0"
gyp verb install installing version: 0.12.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 0.12.0
gyp verb build dir attempting to create "build" dir: /media/win_www/imageSplitApp/node_modules/exiv2/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES, mkdir '/media/win_www/imageSplitApp/node_modules/exiv2/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/win_www/imageSplitApp/node_modules/exiv2
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm verb unsafe-perm in lifecycle false
npm info exiv2@0.5.0 Failed to exec install script
npm verb unlock done using /home/tomino/.npm/_locks/exiv2-d2680eb748b55649.lock for /media/win_www/imageSplitApp/node_modules/exiv2
npm verb stack Error: exiv2@0.5.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1008:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
npm verb pkgid exiv2@0.5.0
npm verb cwd /media/win_www/imageSplitApp
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "exiv2" "--verbose"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! exiv2@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the exiv2@0.5.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the exiv2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls exiv2
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/exiv2
npm info preuninstall exiv2@0.5.0

> exiv2@0.5.0 preuninstall /media/win_www/imageSplitApp/node_modules/exiv2
> rm -rf build/*

npm verb unsafe-perm in lifecycle false
npm info uninstall exiv2@0.5.0
npm verb unbuild rmStuff exiv2@0.5.0 from /media/win_www/imageSplitApp/node_modules
npm info postuninstall exiv2@0.5.0
npm verb gentlyRm vacuuming /media/win_www/imageSplitApp/node_modules/exiv2

npm ERR! Please include the following file with any support request:
npm ERR!     /media/win_www/imageSplitApp/npm-debug.log
```

**Comment by drewish** [comment]
That EACCES error makes me think it's a permissions error. Does it build with sudo?

**Comment by Tomino2112** [comment]
This is with sudo

**Comment by drewish** [comment]
Thoughts on why it dies creating the build directory? Seems like something with your system. You might try cloning the repository and building that.
