### ISSUE TITLE
Cannot npm install on node 0.12 / npm 2.x / OS X El Capitan

### ISSUE THREAD

**Issue by rayshan** [dberesford/exiv2node#39]
Hi,

I was able to install and build 0.6.0 (if I remember correctly...) last month. I believe the only thing that changed was upgrading to El Capitan and upgrading Xcode to the latest. Here's the error now, after running `npm cache clean`:

```
npm WARN package.json cartier@0.0.1 No repository field.
\
> exiv2@0.6.1 install /Users/rayshan/=Projects=/cartier/node_modules/exiv2
> node-gyp rebuild

  CXX(target) Release/obj.target/exiv2/exiv2node.o
../exiv2node.cc:9:10: fatal error: 'exiv2/image.hpp' file not found
#include <exiv2/image.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/exiv2/exiv2node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rayshan/=Projects=/cartier/node_modules/exiv2
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! exiv2@0.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the exiv2@0.6.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the exiv2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls exiv2
npm ERR! There is likely additional logging output above.

> exiv2@0.6.1 preuninstall /Users/rayshan/=Projects=/cartier/node_modules/exiv2
> rm -rf build/*


npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rayshan/=Projects=/cartier/npm-debug.log
```

Thanks!

**Comment by drewish** [comment]
For laughs can you try doing a brew reinstall on the exiv2 lib to see if that helps?

**Comment by rayshan** [comment]
Did that, verified `exiv2` CLI tool runs, then did `npm cache clean`, then `npm install exiv2`, still same error :(

Here's the `npm-debug.log`: https://gist.github.com/rayshan/fdee1a546016a5f9d2c4

**Comment by drewish** [comment]
I've only got El Cap on one machine and I can't replicate this error there.

Looking at the error message:
```
../exiv2node.cc:9:10: fatal error: 'exiv2/image.hpp' file not found
#include <exiv2/image.hpp>
```
It makes me wonder if the include path changed for some reason. 

If you do a `more /usr/local/include/exiv2/exiv2.hpp` are you able to read it?

Can you run `pkg-config --cflags exiv2` so we can see what include paths its using.

**Comment by rayshan** [comment]
Yes `more /usr/local/include/exiv2/exiv2.hpp` return the file content.

`pkg-config --cflags exiv2` returns `-I/usr/local/Cellar/exiv2/0.25/include`, not sure what to make of it.

I tried to install `npm@next-2` under node 0.12 and to install node v4. both didn't help, with same error message.

If the issue is likely with the native `exiv2`, is there a way to cleanly nuke it, or nuke homebrew cache, or install it some other way?

**Comment by simongong** [comment]
+1
same problem occured here and I cannot get it fixed

**Comment by drewish** [comment]
You could try:
```
brew uninstall --force exiv2
brew install  exiv2
```

**Comment by rayshan** [comment]
Unfortunately that didn't help, even with `brew cleanup -s --force` after uninstall. Also I upgraded to node 4.2 today. Still same error. Really sorry we have to bug you about this, could be something weird with our machines, just not sure what it is.

**Comment by drewish** [comment]
For laughs try running: `/usr/local//lib/node_modules/npm/bin/node-gyp-bin/node-gyp rebuild`

I'm getting:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.12.7 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrew/projects/exiv2node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/andrew/.node-gyp/0.12.7/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/andrew/.node-gyp/0.12.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dmodule_root_dir=/Users/andrew/projects/exiv2node',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/exiv2/exiv2node.o
  SOLINK_MODULE(target) Release/exiv2.node
gyp info ok
```

**Comment by rayshan** [comment]
I cloned the repo, ran that command, and am getting:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@4.2.0 | darwin | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rayshan/=Projects=/exiv2node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rayshan/.node-gyp/4.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/rayshan/.node-gyp/4.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/rayshan/=Projects=/exiv2node',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/exiv2/exiv2node.o
../exiv2node.cc:9:10: fatal error: 'exiv2/image.hpp' file not found
#include <exiv2/image.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/exiv2/exiv2node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rayshan/=Projects=/exiv2node
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

I also verified that `/usr/local/include/exiv2/image.hpp` exists and I can `cat` it.

**Comment by drewish** [comment]
Okay so that's exactly the same... I dug in and figured out how to get the Makefile to display the commands it's running:
```
/usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp clean configure
cd build
make V=1
```
Gives me:
```
  c++ '-DNODE_GYP_MODULE_NAME=exiv2' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/andrew/.node-gyp/4.2.0/include/node -I/Users/andrew/.node-gyp/4.2.0/src -I/Users/andrew/.node-gyp/4.2.0/deps/uv/include -I/Users/andrew/.node-gyp/4.2.0/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-threadsafe-statics -stdlib=libc++ -fcxx-exceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/exiv2/exiv2node.o.d.raw  -c -o Release/obj.target/exiv2/exiv2node.o ../exiv2node.cc
  c++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=10.7 -arch x86_64 -L./Release  -o Release/exiv2.node Release/obj.target/exiv2/exiv2node.o -L/usr/local/Cellar/exiv2/0.25/lib -lexiv2
```
I'm not seeing `/usr/local` for an include path so I'm not sure how it's picking it up on my system. 

In  `binding.gyp` we've got `pkg-config --cflags exiv2` which should be returning the include path but it doesn't seem to be getting triggered. I'm wondering if my system has `/usr/local/include` set some place.

While we're debugging can you give me a peek at what version of clang is getting used?
```
gcc -v
```

**Comment by simongong** [comment]
@drewish 
Here is my case:
```
✗ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by drewish** [comment]
Do you mind trying out the [fix-osx-build](https://github.com/dberesford/exiv2node/compare/fix-osx-build?expand=1) branch?

**Comment by rayshan** [comment]
Doing `make V=1` gives me:

```
  c++ '-DNODE_GYP_MODULE_NAME=exiv2' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/rayshan/.node-gyp/4.2.0/include/node -I/Users/rayshan/.node-gyp/4.2.0/src -I/Users/rayshan/.node-gyp/4.2.0/deps/uv/include -I/Users/rayshan/.node-gyp/4.2.0/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-threadsafe-statics -stdlib=libc++ -fcxx-exceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/exiv2/exiv2node.o.d.raw  -c -o Release/obj.target/exiv2/exiv2node.o ../exiv2node.cc
../exiv2node.cc:9:10: fatal error: 'exiv2/image.hpp' file not found
#include <exiv2/image.hpp>
         ^
1 error generated.
make: *** [Release/obj.target/exiv2/exiv2node.o] Error 1
```

`gcc -v` returns exactly the same as @simongong 

Unfortunately `fix-osx-build` branch builds with the same error.

**Comment by drewish** [comment]
@rayshan can you try deleting the entire build directory then running `npm install` to make sure it picked up the changes to the binding.gyp file?

**Comment by drewish** [comment]
Oh actually it looks like I'd screwed up the `pkg-config` command I was trying to use to get the include path... I'll push up another change.

**Comment by drewish** [comment]
@rayshan I amended the commit. Please give it a pull when you have a chance. 

Awesome photos by the way. How are you picking the color for the background on your site? Average RGB value? Histogram clustering? It's a cool effect.

**Comment by rayshan** [comment]
:tada: it's working! Here's what I get:

```
❯ npm install "dberesford/exiv2node#fix-osx-build"
npm WARN package.json cartier@0.0.1 No repository field.
\
> exiv2@0.6.1 install /Users/rayshan/=Projects=/cartier/node_modules/exiv2
> node-gyp rebuild

  CXX(target) Release/obj.target/exiv2/exiv2node.o
  SOLINK_MODULE(target) Release/exiv2.node
exiv2@0.6.1 node_modules/exiv2
└── nan@2.0.9
```

Thanks @drewish for not giving up on us. And thanks for your compliments. If you saw https://shan.io, it's based on a work-in-progress photography static site generator, which uses exiv2node. Sorry it's a little dusty for now. It'll all be open source when done :) The color extraction is based on https://github.com/akfish/node-vibrant. If you would be so kind to provide feedback, you can find me on Twitter, same handle.

I'll wait until patch lands to close this issue.

**Comment by simongong** [comment]
Nice work! :clap:

**Comment by simongong** [comment]
But wait, it still ended up with errors when I tried to install it with node@0.11.13

Any thought? (not related to this thread tho)

```
➜  nvm use 0.11.13
Now using node v0.11.13 (npm v1.4.9)
➜  rm -rf node_modules/exiv2/
➜  npm install "dberesford/exiv2node#fix-osx-build"

> exiv2@0.6.1 install /Users/simon/nodedev/garage/node_modules/exiv2
> node-gyp rebuild

  CXX(target) Release/obj.target/exiv2/exiv2node.o
In file included from ../exiv2node.cc:4:
../node_modules/nan/nan.h:447:32: error: no member named 'SetCounterFunction' in 'v8::Isolate'
    v8::Isolate::GetCurrent()->SetCounterFunction(cb);
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:452:32: error: no member named 'SetCreateHistogramFunction' in
      'v8::Isolate'
    v8::Isolate::GetCurrent()->SetCreateHistogramFunction(cb);
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:457:32: error: no member named 'SetAddHistogramSampleFunction' in
      'v8::Isolate'
    v8::Isolate::GetCurrent()->SetAddHistogramSampleFunction(cb);
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:468:39: error: no member named 'IdleNotification' in 'v8::Isolate'
    return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
           ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:473:32: error: no member named 'LowMemoryNotification' in 'v8::Isolate'
    v8::Isolate::GetCurrent()->LowMemoryNotification();
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../node_modules/nan/nan.h:477:32: error: no member named 'ContextDisposedNotification' in
      'v8::Isolate'
    v8::Isolate::GetCurrent()->ContextDisposedNotification();
    ~~~~~~~~~~~~~~~~~~~~~~~~~  ^
6 errors generated.
make: *** [Release/obj.target/exiv2/exiv2node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/simon/devtools/nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Users/simon/devtools/nvm/v0.11.13/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/simon/nodedev/garage/node_modules/exiv2
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 

> exiv2@0.6.1 preuninstall /Users/simon/nodedev/garage/node_modules/exiv2
> rm -rf build/*

npm ERR! exiv2@0.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the exiv2@0.6.1 install script.
npm ERR! This is most likely a problem with the exiv2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls exiv2
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/simon/devtools/nvm/v0.11.13/bin/node" "/Users/simon/devtools/nvm/v0.11.13/bin/npm" "install" "dberesford/exiv2node#fix-osx-build"
npm ERR! cwd /Users/simon/nodedev/garage
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/simon/nodedev/garage/npm-debug.log
npm ERR! not ok code 0
```

**Comment by drewish** [comment]
@simongong yeah I don't think Nan works with 0.11 you can either upgrade or downgrade and you should be fine.

**Comment by simongong** [comment]
Sure, and I guess it's time for us to upgrade node version! (_It seems that this issue could be closed_ )
