### ISSUE TITLE
"gyp_main.py: error: no such option: --no-parallel" error on install

### ISSUE THREAD

**Issue by royaldark** [dberesford/exiv2node#43]
I'm running into a build issue on install. First, some basic info:

```
$ node -v
v5.3.0
$ npm -v
3.3.12
$ cat /etc/issue
Ubuntu 15.10
```

The install goes well for a while, then errors out with an invocation error on `gyp_main.py`:

```
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/home/joey/.nvm/versions/node/v5.3.0/bin/node',
gyp verb cli   '/home/joey/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.0.3
gyp info using node@5.3.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `python2 -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 5.3.0
gyp verb command install [ '5.3.0' ]
gyp verb install input version string "5.3.0"
gyp verb install installing version: 5.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 5.3.0
gyp verb build dir attempting to create "build" dir: /kb/exif/node_modules/exiv2/build
gyp verb build dir "build" dir needed to be created? /kb/exif/node_modules/exiv2/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /kb/exif/node_modules/exiv2/build/config.gypi
gyp verb config.gypi checking for gypi file: /kb/exif/node_modules/exiv2/config.gypi
gyp verb common.gypi checking for gypi file: /kb/exif/node_modules/exiv2/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn python2
gyp info spawn args [ '/home/joey/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/kb/exif/node_modules/exiv2/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/joey/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/joey/.node-gyp/5.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/joey/.node-gyp/5.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/joey/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/kb/exif/node_modules/exiv2',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/joey/.nvm/versions/node/v5.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-30-generic
```

Any ideas?

**Comment by drewish** [comment]
Kicking off a build on Travis to see if anything pops up there: https://travis-ci.org/dberesford/exiv2node/builds/85205508

I haven't seen that before.

**Comment by drewish** [comment]
Oh... that won't be super useful since we're not testing against node 5: https://github.com/dberesford/exiv2node/blob/master/.travis.yml

**Comment by drewish** [comment]
Want to give https://github.com/nodejs/node-gyp/issues/426#issuecomment-41995907 a try?

**Comment by royaldark** [comment]
https://github.com/nodejs/node-gyp/issues/426#issuecomment-54112531 did it for me. Seems the system version of gyp on Ubuntu boxes is out-of-date.
