### ISSUE TITLE
build fails with node 6.2.0 

### ISSUE THREAD

**Issue by ashish-soni** [dberesford/exiv2node#45]
311 verbose pkgid exiv2@0.6.2
312 verbose cwd /home/ashish/code/ipaas
313 error Linux 3.16.0-38-generic
314 error argv "/home/ashish/.nvm/versions/node/v6.2.2/bin/node" "/home/ashish/.nvm/versions/node/v6.2.2/bin/npm" "install" "exiv2"
315 error node v6.2.2
316 error npm  v3.9.5
317 error code ELIFECYCLE
318 error exiv2@0.6.2 install: `node-gyp rebuild`
318 error Exit status 1
319 error Failed at the exiv2@0.6.2 install script 'node-gyp rebuild'.
319 error Make sure you have the latest version of node.js and npm installed.
319 error If you do, this is most likely a problem with the exiv2 package,
319 error not with npm itself.
319 error Tell the author that this fails on your system:
319 error     node-gyp rebuild
319 error You can get information on how to open an issue for this project with:
319 error     npm bugs exiv2
319 error Or if that isn't available, you can get their info via:
319 error     npm owner ls exiv2
319 error There is likely additional logging output above.
320 verbose exit [ 1, true ]

**Comment by adambrgmn** [comment]
+1

**Comment by sorenkrabbe** [comment]
Build seems to fail with node LTS (currently 6.10.0). Unfortunately I cannot do more than post the build error I receive. Hope someone will look into this issue:

```
make: *** [Release/obj.target/exiv2/exiv2node.o] Error 1
make: Leaving directory `/home/ubuntu/workspace/node_modules/exiv2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.8-c9
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v6.10.0/bin/node" "/home/ubuntu/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/workspace/node_modules/exiv2
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.8.8-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.10.0/bin/node" "/home/ubuntu/.nvm/versions/node/v6.10.0/bin/npm" "install" "exiv2"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```
