### ISSUE TITLE
ERROR buid exiv2node

### ISSUE THREAD

**Issue by emmtte** [dberesford/exiv2node#57]
Hello, with node v11.13.0, impossible to compile exiv2
```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dev/test/node_modules/exiv2
gyp ERR! node -v v11.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! exiv2@0.6.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the exiv2@0.6.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by mariofagac** [comment]
Hi,
I was able to compile with node v10.16.0 and nan v2.14.0 after fixing deprecated 'Call' functions in exiv2node.cc like this:
callback->Call(1, argv); to Nan::Call(callback->GetFunction(), Nan::GetCurrentContext()->Global(), 1, argv); ...
